### ISSUE TITLE
Make more bike sheds!

### ISSUE THREAD

**Issue by spikehains** [kkostrzewa/screambot#3]

**Comment by kkostrzewa** [comment]
started bikeshed from appreciate points.

**Comment by kkostrzewa** [comment]
creating a level base has proven problematic. nevertheless, he persisted

**Comment by spikehains** [comment]
you got this. do it for the nouns.

**Comment by kkostrzewa** [comment]
Problems:
![image](https://user-images.githubusercontent.com/19849201/79688225-dc007700-821a-11ea-8e7f-d0391003548f.png)

**Comment by kkostrzewa** [comment]
Resolved, r4r

![image](https://user-images.githubusercontent.com/19849201/79688288-5f21cd00-821b-11ea-97c4-e6ac7bdff0b7.png)
